Datafiles =
{
    { Name = "Back-up files", Value = 0 },
    { Name = "Archived files", Value = 1 },
    { Name = "Canceled accounts", Value = 2 },
    { Name = "History data", Value = 3 },
    { Name = "Canceled passwords", Value = 4 },
    { Name = "System usage report", Value = 5 },
    { Name = "System activity", Value = 6 },
    { Name = "Access request log", Value = 7 },
    { Name = "E-mail data", Value = 8 },
    { Name = "Routing requests", Value = 9 },
    { Name = "Bank acct. numbers", Value = 10 },
    { Name = "Corporate profile", Value = 11 },
    { Name = "Personnel dossiers", Value = 12 },
    { Name = "Employee scheduling", Value = 13 },
    { Name = "Client information", Value = 14 },
    { Name = "Project records", Value = 15 },
    { Name = "Open project data", Value = 16 },
    { Name = "Project expense report", Value = 17 },
    { Name = "Project requisition", Value = 18 },
    { Name = "Project utilities", Value = 19 },
    { Name = "Security records", Value = 20 },
    { Name = "Contact dossiers", Value = 21 },
    { Name = "Surveillance data", Value = 22 },
    { Name = "Equipment permits", Value = 23 },
    { Name = "Lone Star reports", Value = 24 },
    { Name = "Archived files", Value = 25 },
    { Name = "Project folders", Value = 26 },
    { Name = "Closed projects", Value = 27 },
    { Name = "Project expense report", Value = 28 },
    { Name = "Failed prototypes", Value = 29 },
    { Name = "Competitor profiles", Value = 30 },
    { Name = "Competitor products", Value = 31 },
    { Name = "Competitor marketing", Value = 32 },
    { Name = "Competitor security", Value = 33 },
    { Name = "Competitor budgets", Value = 34 },
    { Name = "Sales information", Value = 35 },
    { Name = "Public relations", Value = 36 },
    { Name = "Customer files", Value = 37 },
    { Name = "Advertising info", Value = 38 },
    { Name = "Marketing report", Value = 39 },
    { Name = "Entertainment data", Value = 40 },
    { Name = "Educational data", Value = 41 },
    { Name = "BTL data", Value = 42 },
    { Name = "Experimental data", Value = 43 },
    { Name = "Toxic data", Value = 44 },
    { Name = "Bank acct. numbers", Value = 45 },
    { Name = "Corporate account", Value = 46 },
    { Name = "Local accounts", Value = 47 },
    { Name = "Security expenses", Value = 48 },
    { Name = "Capital expidenture", Value = 49 },
    { Name = "Long range goals", Value = 50 },
    { Name = "Shadowrun information", Value = 51 },
    { Name = "Strike Team orders", Value = 52 },
    { Name = "Blackmail Information", Value = 53 },
    { Name = "Prototype blueprint", Value = 54 },
    { Name = "Domestic law", Value = 55 },
    { Name = "International law", Value = 56 },
    { Name = "Tribal law", Value = 57 },
    { Name = "Pending lawsuits", Value = 58 },
    { Name = "Contact dossiers", Value = 59 },
    { Name = "Current inmates", Value = 60 },
    { Name = "Previous inmates", Value = 61 },
    { Name = "Psychiatric reports", Value = 62 },
    { Name = "Parole files", Value = 63 },
    { Name = "Contact dossiers", Value = 64 },
    { Name = "Open case files", Value = 65 },
    { Name = "Closed case files", Value = 66 },
    { Name = "Equipment permits", Value = 67 },
    { Name = "Outstanding warrants", Value = 68 },
    { Name = "Unsolved cases", Value = 69 },
    { Name = "None", Value = 255 }
}
