Datafiles =
{
    { Name = "Back-up Files", Value = 0 },
    { Name = "Archived Files", Value = 1 },
    { Name = "Canceled Accounts", Value = 2 },
    { Name = "History Data", Value = 3 },
    { Name = "Canceled Passwords", Value = 4 },
    { Name = "System Usage Report", Value = 5 },
    { Name = "System Activity", Value = 6 },
    { Name = "Access Request Log", Value = 7 },
    { Name = "E-mail Data", Value = 8 },
    { Name = "Routing Requests", Value = 9 },
    { Name = "Bank Acct. Numbers", Value = 10 },
    { Name = "Corporate Profile", Value = 11 },
    { Name = "Personnel Dossiers", Value = 12 },
    { Name = "Employee Scheduling", Value = 13 },
    { Name = "Client Information", Value = 14 },
    { Name = "Project Records", Value = 15 },
    { Name = "Open Project Data", Value = 16 },
    { Name = "Project Expense Report", Value = 17 },
    { Name = "Project Requisition", Value = 18 },
    { Name = "Project Utilities", Value = 19 },
    { Name = "Security Records", Value = 20 },
    { Name = "Contact Dossiers", Value = 21 },
    { Name = "Surveillance Data", Value = 22 },
    { Name = "Equipment Permits", Value = 23 },
    { Name = "Lone Star Reports", Value = 24 },
    { Name = "Archived Files", Value = 25 },
    { Name = "Project Folders", Value = 26 },
    { Name = "Closed Projects", Value = 27 },
    { Name = "Project Expense Report", Value = 28 },
    { Name = "Failed Prototypes", Value = 29 },
    { Name = "Competitor Profiles", Value = 30 },
    { Name = "Competitor Products", Value = 31 },
    { Name = "Competitor Marketing", Value = 32 },
    { Name = "Competitor Security", Value = 33 },
    { Name = "Competitor Budgets", Value = 34 },
    { Name = "Sales Information", Value = 35 },
    { Name = "Public Relations", Value = 36 },
    { Name = "Customer Files", Value = 37 },
    { Name = "Advertising Info", Value = 38 },
    { Name = "Marketing Report", Value = 39 },
    { Name = "Entertainment Data", Value = 40 },
    { Name = "Educational Data", Value = 41 },
    { Name = "BTL Data", Value = 42 },
    { Name = "Experimental Data", Value = 43 },
    { Name = "Toxic Data", Value = 44 },
    { Name = "Bank Acct. Numbers", Value = 45 },
    { Name = "Corporate Account", Value = 46 },
    { Name = "Local Accounts", Value = 47 },
    { Name = "Security Expenses", Value = 48 },
    { Name = "Capital Expidenture", Value = 49 },
    { Name = "Long Range Goals", Value = 50 },
    { Name = "Shadowrun Information", Value = 51 },
    { Name = "Strike Team Orders", Value = 52 },
    { Name = "Blackmail Information", Value = 53 },
    { Name = "Prototype Blueprint", Value = 54 },
    { Name = "Domestic Law", Value = 55 },
    { Name = "International Law", Value = 56 },
    { Name = "Tribal Law", Value = 57 },
    { Name = "Pending Lawsuits", Value = 58 },
    { Name = "Contact Dossiers", Value = 59 },
    { Name = "Current Inmates", Value = 60 },
    { Name = "Previous Inmates", Value = 61 },
    { Name = "Psychiatric Reports", Value = 62 },
    { Name = "Parole Files", Value = 63 },
    { Name = "Contact Dossiers", Value = 64 },
    { Name = "Open Case Files", Value = 65 },
    { Name = "Closed Case Files", Value = 66 },
    { Name = "Equipment Permits", Value = 67 },
    { Name = "Outstanding Warrants", Value = 68 },
    { Name = "Unsolved Cases", Value = 69 },
    { Name = "None", Value = 255 }
}
