Items =
{
    "Nothing",
    "Streetline Special",
    "Model 101T LP",
    "American L36 LP",
    "Security 500 LP",
    "Warhawk HP",
    "Max-Power HP",
    "Predator HP",
    "AK-97 SMG",
    "HK227-S SMG",
    "Mach 22 SMG",
    "Allegiance Shotgun",
    "Roomsweeper Shotgun",
    "Frag Grenade",
    "Scatter Grenade",
    "Concussion Grenade",
    "Medkit",
    "Stim Patch",
    "Trauma Patch",
    "Fetish",
    "Maglock Passkey",
    "Electronic Kit",
    "Smart Goggles",
    "Enchanted Dagger",
    "Power Focus",
    "Flame Dart SF",
    "Flame Bolt SF",
    "Hellblast SF",
    "Invisibility SF",
    "Sleep SF",
    "Stink SF",
    "Super Barrier SF",
    "Mana Zap SF",
    "Mana Blast SF",
    "Mana Storm SF",
    "Rockskin SF",
    "Heal Wounds SF",
    "Confusion SF",
    "Barrier SF",
    "Protection Talisman",
    "Combat Sense Spell Lock",
    "Rat Totem",
    "Gator Totem",
    "Bear Totem",
    "Armor Vest",
    "Armor Clothing",
    "Armor Jacket",
    "Vest With Plates",
    "Lined Duster",
    "Light Combat Armor",
    "Heavy Combat Armor"
}
