Weapons =
{
    "Melee",
    "Streetline Special",
    "Model 101T LP",
    "American L36 LP",
    "Security 500 LP",
    "Warhawk HP",
    "Max-Power HP",
    "Predator HP",
    "AK-97 SMG",
    "HK227-S SMG",
    "Mach 22 SMG",
    "Allegiance Shotgun",
    "Roomsweeper Shotgun",
    "Frag Grenade",
    "Scatter Grenade",
    "Concussion Grenade",
    "???",
    "???",
    "???",
    "???",
    "???",
    "Electronic Kit",
}
